### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by plexus** [clojusc/ring-redis-session#2]
Hey, just wanted to say thanks for maintaining this lib. I switched from the original to your fork some time ago because it was no longer maintained. Been using it succesfully for storing sessions on https://lambdaisland.com.

I noticed on the latest update that you changed the namespace name, which makes sense. Have you considered also releasing it as ring-redis-session? Might make it more clear that this fork is living its own life now.

Cheers :)

**Comment by oubiwann** [comment]
Hey! You're very welcome :-) Glad you're liking it. (There's a project at NASA that's using this fork, too -- so you're in good company :-))

That's a great idea about a release with that name. Maybe I can hit that this week sometime. I'll ping you to let you know.

**Comment by oubiwann** [comment]
Okay, couldn't resist -- I've updated, renamed, and pushed to Clojars:
 * https://clojars.org/clojusc/ring-redis-session

Enjoy!
