### ISSUE TITLE
Infinite loop if constructor called without extra options

### ISSUE THREAD

**Issue by milt** [clojusc/ring-redis-session#3]
See the first arity of `redis-store`
Should probably have an empty map as the second arg.
https://github.com/clojusc/ring-redis-session/blob/dev/src/ring/redis/session.clj#L64

**Comment by oubiwann** [comment]
Yikes! Thanks for the catch.

**Comment by oubiwann** [comment]
The fix has been released in 3.2.0.

Thanks again :-)
